//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilterSettingsView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilterSettingsView.LocalResource", typeof(LocalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string BTN_CLOSE {
            get {
                return ResourceManager.GetString("BTN_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CombineSideWays.
        /// </summary>
        public static string BTN_COMBINE_SIDEWAYS {
            get {
                return ResourceManager.GetString("BTN_COMBINE_SIDEWAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CombineVertical.
        /// </summary>
        public static string BTN_COMBINE_VERTICAL {
            get {
                return ResourceManager.GetString("BTN_COMBINE_VERTICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewQc4File.
        /// </summary>
        public static string BTN_CREATE_QC4 {
            get {
                return ResourceManager.GetString("BTN_CREATE_QC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataMerge.
        /// </summary>
        public static string BTN_DATA_MERGE {
            get {
                return ResourceManager.GetString("BTN_DATA_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataOutput.
        /// </summary>
        public static string BTN_DATA_OUTPUT {
            get {
                return ResourceManager.GetString("BTN_DATA_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string BTN_EXIT {
            get {
                return ResourceManager.GetString("BTN_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalData.
        /// </summary>
        public static string BTN_EXTERNAL_DATA {
            get {
                return ResourceManager.GetString("BTN_EXTERNAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string BTN_OPEN {
            get {
                return ResourceManager.GetString("BTN_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BTN_SAVE {
            get {
                return ResourceManager.GetString("BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveAs.
        /// </summary>
        public static string BTN_SAVE_AS {
            get {
                return ResourceManager.GetString("BTN_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenMatch.
        /// </summary>
        public static string BTN_SCREEN_MATCH {
            get {
                return ResourceManager.GetString("BTN_SCREEN_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwapData.
        /// </summary>
        public static string BTN_SWAP_DATA {
            get {
                return ResourceManager.GetString("BTN_SWAP_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToSheet.
        /// </summary>
        public static string BTN_TOSHEET {
            get {
                return ResourceManager.GetString("BTN_TOSHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MA 01 FORMAT.
        /// </summary>
        public static string CB_ITEM_01_MA01 {
            get {
                return ResourceManager.GetString("CB_ITEM_01_MA01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MA Comma Separated in a Cell.
        /// </summary>
        public static string CB_ITEM_02_MA_COMMA_SEPERATED {
            get {
                return ResourceManager.GetString("CB_ITEM_02_MA_COMMA_SEPERATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        public static string CB_MA_SPSS_01 {
            get {
                return ResourceManager.GetString("CB_MA_SPSS_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string CB_MA_SPSS_02 {
            get {
                return ResourceManager.GetString("CB_MA_SPSS_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ×.
        /// </summary>
        public static string CELL_OFF {
            get {
                return ResourceManager.GetString("CELL_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ○.
        /// </summary>
        public static string CELL_ON {
            get {
                return ResourceManager.GetString("CELL_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.
        /// </summary>
        public static string GTT_FS_CB_ITEM_VALUE_EQUALS {
            get {
                return ResourceManager.GetString("GTT_FS_CB_ITEM_VALUE_EQUALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.
        /// </summary>
        public static string GTT_FS_CB_ITEM_VALUE_GREATER_THAN {
            get {
                return ResourceManager.GetString("GTT_FS_CB_ITEM_VALUE_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string GTT_FS_CB_ITEM_VALUE_GREATER_THAN_OR_EQUAL_TO {
            get {
                return ResourceManager.GetString("GTT_FS_CB_ITEM_VALUE_GREATER_THAN_OR_EQUAL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string GTT_FS_CB_ITEM_VALUE_LESS_OR_GREATER {
            get {
                return ResourceManager.GetString("GTT_FS_CB_ITEM_VALUE_LESS_OR_GREATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.
        /// </summary>
        public static string GTT_FS_CB_ITEM_VALUE_LESS_THAN {
            get {
                return ResourceManager.GetString("GTT_FS_CB_ITEM_VALUE_LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        public static string GTT_FS_CB_ITEM_VALUE_LESS_THAN_OR_EQUAL_TO {
            get {
                return ResourceManager.GetString("GTT_FS_CB_ITEM_VALUE_LESS_THAN_OR_EQUAL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        public static string LABEL_AND {
            get {
                return ResourceManager.GetString("LABEL_AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回答タイプ.
        /// </summary>
        public static string LABEL_ANSWERTYPE {
            get {
                return ResourceManager.GetString("LABEL_ANSWERTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on Total Respondents.
        /// </summary>
        public static string LABEL_BASED_RESPONDENTS {
            get {
                return ResourceManager.GetString("LABEL_BASED_RESPONDENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Blank).
        /// </summary>
        public static string LABEL_BLANK {
            get {
                return ResourceManager.GetString("LABEL_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode (Encoding option in SPSS).
        /// </summary>
        public static string LABEL_CB_UNICODE_SPSS {
            get {
                return ResourceManager.GetString("LABEL_CB_UNICODE_SPSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character For [Excluded].
        /// </summary>
        public static string LABEL_CHARACTER_FOR_EXCLUDED {
            get {
                return ResourceManager.GetString("LABEL_CHARACTER_FOR_EXCLUDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択肢数.
        /// </summary>
        public static string LABEL_CHOICE_COUNT {
            get {
                return ResourceManager.GetString("LABEL_CHOICE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string LABEL_CLOSE {
            get {
                return ResourceManager.GetString("LABEL_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Definition File.
        /// </summary>
        public static string LABEL_CONVERSION_DEFINITION_FILE {
            get {
                return ResourceManager.GetString("LABEL_CONVERSION_DEFINITION_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条件アイテム.
        /// </summary>
        public static string LABEL_CRITERIA_VARIABLE {
            get {
                return ResourceManager.GetString("LABEL_CRITERIA_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分類アイテム.
        /// </summary>
        public static string LABEL_CRITERION_VARIABLE {
            get {
                return ResourceManager.GetString("LABEL_CRITERION_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        public static string LABEL_DBL_LEFT_ARROW {
            get {
                return ResourceManager.GetString("LABEL_DBL_LEFT_ARROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        public static string LABEL_DBL_RIGHT_ARROW {
            get {
                return ResourceManager.GetString("LABEL_DBL_RIGHT_ARROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string LABEL_EXECUTE {
            get {
                return ResourceManager.GetString("LABEL_EXECUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string LABEL_EXPORT {
            get {
                return ResourceManager.GetString("LABEL_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出力先フォルダ指定.
        /// </summary>
        public static string LABEL_EXPORT_PATH {
            get {
                return ResourceManager.GetString("LABEL_EXPORT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Setting.
        /// </summary>
        public static string LABEL_EXPORT_SETTING {
            get {
                return ResourceManager.GetString("LABEL_EXPORT_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Type.
        /// </summary>
        public static string LABEL_EXPORT_TYPE {
            get {
                return ResourceManager.GetString("LABEL_EXPORT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Format.
        /// </summary>
        public static string LABEL_FILE_FORMAT {
            get {
                return ResourceManager.GetString("LABEL_FILE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Setting.
        /// </summary>
        public static string LABEL_FILTER_SETTING {
            get {
                return ResourceManager.GetString("LABEL_FILTER_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 絞込み条件.
        /// </summary>
        public static string LABEL_FILTERING_CRITERIA {
            get {
                return ResourceManager.GetString("LABEL_FILTERING_CRITERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string LABEL_HYPHEN {
            get {
                return ResourceManager.GetString("LABEL_HYPHEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator for [No Answer] (SA/MA).
        /// </summary>
        public static string LABEL_INDICATOR_FNA_SA_MA_SPSS {
            get {
                return ResourceManager.GetString("LABEL_INDICATOR_FNA_SA_MA_SPSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator For [NoAnswer].
        /// </summary>
        public static string LABEL_INDICATOR_FOR_NO_ANSWER {
            get {
                return ResourceManager.GetString("LABEL_INDICATOR_FOR_NO_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MA Variables.
        /// </summary>
        public static string LABEL_MA_VARIABLES {
            get {
                return ResourceManager.GetString("LABEL_MA_VARIABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Label.
        /// </summary>
        public static string LABEL_MULTIDIGIT_NUMBERS {
            get {
                return ResourceManager.GetString("LABEL_MULTIDIGIT_NUMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Choice Numbers.
        /// </summary>
        public static string LABEL_OP_CHOICE_NUMBERS {
            get {
                return ResourceManager.GetString("LABEL_OP_CHOICE_NUMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output MA Choice.
        /// </summary>
        public static string LABEL_OP_MA_CHOICE_SPSS {
            get {
                return ResourceManager.GetString("LABEL_OP_MA_CHOICE_SPSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output ON(1)/OFF(0).
        /// </summary>
        public static string LABEL_OP_ON_OFF_0 {
            get {
                return ResourceManager.GetString("LABEL_OP_ON_OFF_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output ON(1)/OFF(Blank).
        /// </summary>
        public static string LABEL_OP_ON_OFF_BLANK {
            get {
                return ResourceManager.GetString("LABEL_OP_ON_OFF_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 演算子.
        /// </summary>
        public static string LABEL_OPERATOR {
            get {
                return ResourceManager.GetString("LABEL_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string LABEL_OR {
            get {
                return ResourceManager.GetString("LABEL_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Options.
        /// </summary>
        public static string LABEL_OUTPUT_OPTIONS {
            get {
                return ResourceManager.GetString("LABEL_OUTPUT_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad With Leading Spaces.
        /// </summary>
        public static string LABEL_PAD_WITH_LEADING_SPACES {
            get {
                return ResourceManager.GetString("LABEL_PAD_WITH_LEADING_SPACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad With Leading Zeroes.
        /// </summary>
        public static string LABEL_PAD_WITH_LEADING_ZEROES {
            get {
                return ResourceManager.GetString("LABEL_PAD_WITH_LEADING_ZEROES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 質問文.
        /// </summary>
        public static string LABEL_QUESTION {
            get {
                return ResourceManager.GetString("LABEL_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string LABEL_SINGLE_LEFT_ARROW {
            get {
                return ResourceManager.GetString("LABEL_SINGLE_LEFT_ARROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string LABEL_SINGLE_RIGHT_ARROW {
            get {
                return ResourceManager.GetString("LABEL_SINGLE_RIGHT_ARROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split by 256 columns.
        /// </summary>
        public static string LABEL_SPLIT_BY_256 {
            get {
                return ResourceManager.GetString("LABEL_SPLIT_BY_256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string LABEL_STAR {
            get {
                return ResourceManager.GetString("LABEL_STAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値.
        /// </summary>
        public static string LABEL_VALUE {
            get {
                return ResourceManager.GetString("LABEL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables To Export(SAMPLEID Required).
        /// </summary>
        public static string LABEL_VARIABLES_TO_EXPORT {
            get {
                return ResourceManager.GetString("LABEL_VARIABLES_TO_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Layout OutPut.
        /// </summary>
        public static string LABEL_VERICAL_LAYOUT {
            get {
                return ResourceManager.GetString("LABEL_VERICAL_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string LABEL_ZERO {
            get {
                return ResourceManager.GetString("LABEL_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is a description of the sentence. Because the character is small, it might be better a little more big. This sentence is for Dummies..
        /// </summary>
        public static string LBL_COMBINE_SIDEWAYS {
            get {
                return ResourceManager.GetString("LBL_COMBINE_SIDEWAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is a description of the sentence. Because the character is small, it might be better a little more big. This sentence is for Dummies..
        /// </summary>
        public static string LBL_COMBINE_VERTICAL {
            get {
                return ResourceManager.GetString("LBL_COMBINE_VERTICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is a description of the sentence. Because the character is small, it might be better a little more big. This sentence is for Dummies..
        /// </summary>
        public static string LBL_CREATE_QC4 {
            get {
                return ResourceManager.GetString("LBL_CREATE_QC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Export.
        /// </summary>
        public static string LBL_DATA_EXPORT {
            get {
                return ResourceManager.GetString("LBL_DATA_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is a description of the sentence. Because the character is small, it might be better a little more big. This sentence is for Dummies..
        /// </summary>
        public static string LBL_EXTERNAL_DATA {
            get {
                return ResourceManager.GetString("LBL_EXTERNAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName.
        /// </summary>
        public static string LBL_FILE_NAME {
            get {
                return ResourceManager.GetString("LBL_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is a description of the sentence. Because the character is small, it might be better a little more big. This sentence is for Dummies..
        /// </summary>
        public static string LBL_SCREEN_MATCH {
            get {
                return ResourceManager.GetString("LBL_SCREEN_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch Data in Swap Data.
        /// </summary>
        public static string LBL_SWAP_ERROR {
            get {
                return ResourceManager.GetString("LBL_SWAP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Data .
        /// </summary>
        public static string TITLE_SDE_WINDOW {
            get {
                return ResourceManager.GetString("TITLE_SDE_WINDOW", resourceCulture);
            }
        }
    }
}
