//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyGeneration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyGeneration.AdminResource", typeof(AdminResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Activation Key!.
        /// </summary>
        internal static string ERROR_MSG__INVALID_KEY {
            get {
                return ResourceManager.GetString("ERROR_MSG__INVALID_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date not selected!!.
        /// </summary>
        internal static string ERROR_MSG_DATE {
            get {
                return ResourceManager.GetString("ERROR_MSG_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error data! Please try again....
        /// </summary>
        internal static string ERROR_MSG_ERROR_DATA {
            get {
                return ResourceManager.GetString("ERROR_MSG_ERROR_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value!.
        /// </summary>
        internal static string ERROR_MSG_INVALID_DATA {
            get {
                return ResourceManager.GetString("ERROR_MSG_INVALID_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to Close?.
        /// </summary>
        internal static string MESSAGE_CLOSE_CONF {
            get {
                return ResourceManager.GetString("MESSAGE_CLOSE_CONF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete ?.
        /// </summary>
        internal static string MESSAGE_DELETE_CONF {
            get {
                return ResourceManager.GetString("MESSAGE_DELETE_CONF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickCross.
        /// </summary>
        internal static string MESSAGE_QC {
            get {
                return ResourceManager.GetString("MESSAGE_QC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a row or cell to paste the data..
        /// </summary>
        internal static string WARNING_MSG_COPYPASTE_1 {
            get {
                return ResourceManager.GetString("WARNING_MSG_COPYPASTE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of columns to be pasted does not match according to the selected cell. Please try again....
        /// </summary>
        internal static string WARNING_MSG_COPYPASTE_2 {
            get {
                return ResourceManager.GetString("WARNING_MSG_COPYPASTE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System information is empty! Please enter valid data for key generation.
        /// </summary>
        internal static string WARNING_MSG_DATA {
            get {
                return ResourceManager.GetString("WARNING_MSG_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryption failed in the row.
        /// </summary>
        internal static string WARNING_MSG_DPT_FAILED_ROW {
            get {
                return ResourceManager.GetString("WARNING_MSG_DPT_FAILED_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an activation key!.
        /// </summary>
        internal static string WARNING_MSG_ENTER_KEY {
            get {
                return ResourceManager.GetString("WARNING_MSG_ENTER_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key generation failed in the row .
        /// </summary>
        internal static string WARNING_MSG_GEN_FAILED_ROW {
            get {
                return ResourceManager.GetString("WARNING_MSG_GEN_FAILED_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data for key generation.
        /// </summary>
        internal static string WARNING_MSG_INVALID_DATA {
            get {
                return ResourceManager.GetString("WARNING_MSG_INVALID_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in row with Sl No..
        /// </summary>
        internal static string WARNING_MSG_ROW {
            get {
                return ResourceManager.GetString("WARNING_MSG_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a row with system ID for key generation..
        /// </summary>
        internal static string WARNING_MSG_ROW_WITH_ID {
            get {
                return ResourceManager.GetString("WARNING_MSG_ROW_WITH_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one system information with value for key generation.
        /// </summary>
        internal static string WARNING_MSG_SELECT_ATLEAST_ONE {
            get {
                return ResourceManager.GetString("WARNING_MSG_SELECT_ATLEAST_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter data in selected system information for key generation : .
        /// </summary>
        internal static string WARNING_MSG_SELECT_INFO {
            get {
                return ResourceManager.GetString("WARNING_MSG_SELECT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a row for key generation!.
        /// </summary>
        internal static string WARNING_MSG_SELECT_ROW_1 {
            get {
                return ResourceManager.GetString("WARNING_MSG_SELECT_ROW_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a row to delete!.
        /// </summary>
        internal static string WARNING_MSG_SELECT_ROW_2 {
            get {
                return ResourceManager.GetString("WARNING_MSG_SELECT_ROW_2", resourceCulture);
            }
        }
    }
}
