/*
[df:title]
データ加工メイン画面で利用するデータ加工リスト情報を取得する

[df:description]
QCWebIdが必須です
*/
-- #TDataEditListSelect#
-- !TDataEditListSelectPmb!
-- !!Decimal QCWebId!!
-- !!int? LatestFlag!!
-- !!int? ExecuteFlag!!

SELECT 
      DATAEDIT.DATA_EDIT_ID
    , DATAEDIT.QCWEBID
    , DATAEDIT.EXECUTE_NO
    , DATAEDIT.EXECUTE_FLAG
    , DATAEDIT.EDIT_MENU_MASTER_ID
    , DATAEDIT.CONDITION_ITEM_VIEW_NAME
    , DATAEDIT.TARGET_ITEM_VIEW_NAME
    , DATAEDIT.STATUS
    , DATAEDIT.LATEST_FLAG
    , DATAEDIT.DERIVED_DATA_EDIT_ID
    , DATAEDIT.DELETE_RESERVE_FLAG
	, DATAEDIT.DESCRIPTION
	, DATAEDIT.EDIT_FLAG
    , PAC_DATAPROCESS_CHECK.GET_TARGET_ITEMID_CSV(DATAEDIT.DATA_EDIT_ID) AS TARGET_CSV
    , PAC_DATAPROCESS_CHECK.GET_CONDITION_ITEMID_CSV(DATAEDIT.DATA_EDIT_ID) AS CONDITION_CSV
	, NEWITEM.FORMULA_STRING
FROM 
    T_DATA_EDIT_LIST DATAEDIT
    LEFT OUTER JOIN T_DATA_PROCESS_NEW_ITEM NEWITEM 
    ON DATAEDIT.DATA_EDIT_ID = NEWITEM.DATA_EDIT_ID
WHERE 
        DATAEDIT.QCWEBID = /*pmb.QCWebId*/5 
    /*IF pmb.LatestFlag == 1*/
    AND DATAEDIT.LATEST_FLAG = 1
    /*END*/
    /*IF pmb.LatestFlag == 0*/
    AND DATAEDIT.STATUS = '1'
    /*END*/
    /*IF pmb.ExecuteFlag != null*/
    AND DATAEDIT.EXECUTE_FLAG = /*pmb.ExecuteFlag*/1
    /*END*/
ORDER BY 
    DATAEDIT.EXECUTE_NO ASC
;