/*
[df:title]
環境設定にデータ登録

[df:description]
環境設定にデフォルト環境設定の言語指定のデータを登録します。

$Id: TDefaultEnvBhv_insertBasicData.sql 5020 2011-04-03 17:43:00Z ykanamo@JOPS.LOCAL $
*/
-- !TDefaultEnvInsertBasicDataPmb!
-- !!Decimal Qcwebid!!
-- !!String UserLanguage!!
INSERT INTO T_DEFAULT_ENV
( QCWEBID
,NOANSWER_DENOMINATOR_FLAG
,VISIBLE_UNFIT_FLAG
,NOANSWER_UNFIT_FLAG
,WEIGHTBACK_FLAG
,CELL_JOINCELL_JOIN_FLAG
,CHART_DIRECTION_GT_FLAG
,CHART_DIRECTION_CROSS_FLAG
,NOANSWER_TARGET_FLAG
,NOANSWER_AXIS_FLAG
,UNFIT_TARGET_FLAG
,UNFIT_AXIS_FLAG
,TOTALNUM_FLAG
,RATE_DIFF_COLOR_MINUS5
,RATE_DIFF_COLOR_MINUS10
,RATE_DIFF_COLOR_PLUS5
,RATE_DIFF_COLOR_PLUS10
,GRAPH_TYPE_SA
,GRAPH_TYPE_SA_MATRIX
,GRAPH_TYPE_MA_SIMPLE
,GRAPH_TYPE_MA_CROSS
,GRAPH_TYPE_MA_MATRIX
,GRAPH_TYPE_N_RATE
,GRAPH_TYPE_N_RANKING
,SET_EXECUTE_FLAG
,TITLE_ALL
,TITLE_AXIS_ALL
,TITLE_NOANSWER
,TITLE_UNFIT
,TITLE_BEFORE_WB
,FLAG_STATISTICS_PARAMETER
,TITLE_STATISTICS_PARAMETER
,FLAG_TOTAL
,TITLE_TOTAL
,DP_SUM
,FLAG_AVR
,TITLE_AVR
,DP_AVR
,FLAG_SD
,TITLE_SD
,DP_SD
,FLAG_MIN
,TITLE_MIN
,DP_MIN
,FLAG_MAX
,TITLE_MAX
,DP_MAX
,FLAG_MEDIAN
,TITLE_MEDIAN
,DP_MEDIAN
,DP_WEIGHT
,DP_WEIGHT_AVR
,EXCEL_TYPE
,PP_TYPE
,LAST_UPDATE_USER
,LAST_UPDATE_DATETIME
,TEST_GT_FLAG
,TEST_CROSS_FLAG
,TEST_TYPE_GT
,TEST_TYPE_CROSS
,TEST_SIGNIFICANCE_LV_GT
,TEST_SIGNIFICANCE_LV_CROSS
)
SELECT 
/*pmb.Qcwebid*/90000001
,NOANSWER_DENOMINATOR_FLAG
,VISIBLE_UNFIT_FLAG
,NOANSWER_UNFIT_FLAG
,WEIGHTBACK_FLAG
,CELL_JOINCELL_JOIN_FLAG
,CHART_DIRECTION_GT_FLAG
,CHART_DIRECTION_CROSS_FLAG
,NOANSWER_TARGET_FLAG
,NOANSWER_AXIS_FLAG
,UNFIT_TARGET_FLAG
,UNFIT_AXIS_FLAG
,TOTALNUM_FLAG
,RATE_DIFF_COLOR_MINUS5
,RATE_DIFF_COLOR_MINUS10
,RATE_DIFF_COLOR_PLUS5
,RATE_DIFF_COLOR_PLUS10
,GRAPH_TYPE_SA
,GRAPH_TYPE_SA_MATRIX
,GRAPH_TYPE_MA_SIMPLE
,GRAPH_TYPE_MA_CROSS
,GRAPH_TYPE_MA_MATRIX
,GRAPH_TYPE_N_RATE
,GRAPH_TYPE_N_RANKING
,SET_EXECUTE_FLAG
,TITLE_ALL
,TITLE_AXIS_ALL
,TITLE_NOANSWER
,TITLE_UNFIT
,TITLE_BEFORE_WB
,FLAG_STATISTICS_PARAMETER
,TITLE_STATISTICS_PARAMETER
,FLAG_TOTAL
,TITLE_TOTAL
,DP_SUM
,FLAG_AVR
,TITLE_AVR
,DP_AVR
,FLAG_SD
,TITLE_SD
,DP_SD
,FLAG_MIN
,TITLE_MIN
,DP_MIN
,FLAG_MAX
,TITLE_MAX
,DP_MAX
,FLAG_MEDIAN
,TITLE_MEDIAN
,DP_MEDIAN
,DP_WEIGHT
,DP_WEIGHT_AVR
,NULL --EXCEL_TYPE
,NULL --PP_TYPE
,NULL --LAST_UPDATE_USER
,NULL --LAST_UPDATE_DATETIME
,TEST_GT_FLAG
,TEST_CROSS_FLAG
,TEST_TYPE_GT
,TEST_TYPE_CROSS
,TEST_SIGNIFICANCE_LV_GT
,TEST_SIGNIFICANCE_LV_CROSS
FROM T_DEFAULT_ENV_BASE BASE
WHERE BASE.LANGUAGE = /*pmb.UserLanguage*/'ja-JP'
;