/*
[df:title]
データ加工系画面で利用するアイテム一覧情報を取得する

[df:description]
すべての条件値が必須です
*/
-- #TItemInfoQuestionsDP#
-- !TItemInfoQuestionsDPPmb!
-- !!Decimal QCWebId!!
-- !!int ExecuteNo!!
-- !!List<String> AnswerType!!

SELECT 
      ITEM.ITEM_INFO_ID
    , ITEM.QCWEBID
    , ITEM.ITEM_NAME
    , ITEM.SOURCE_DIV
    , ITEM.ITEMNO
    , ITEM.ITEM_TYPE
    , ITEM.ANSWER_TYPE
    , ITEM.SORT_NUMBER
    , ITEM.MATRIX_DIV
    , ITEM.LV1TITLE
    , ITEM.LV2TITLE 
    , ITEM.ORIGINAL_LV1TITLE
    , ITEM.ORIGINAL_LV2TITLE
    , ITEM.CATEGORY_EDIT_ID
    , ITEM.DATA_EDIT_ID
    , ITEM.STATUS
    , ITEM.COMPEL_ITEM_CHANGE_FLAG
    , ITEM.SORT_FLAG
    , ITEM.SORT_RANGE
    , ITEM.MULTIVARIATE_FLAG
    , NVL(NVL(ITEMCATE.CATECNT, PARENTCATE.CATECNT), 0) AS CATEGORY_COUNT --カテゴリ数
    , DECODE(ITEM.MATRIX_DIV, 1, MATRIXCOUNT.CHILDITEMCNT, 0) AS CHILD_ITEM_COUNT --親マトの場合、子アイテム数
    --データ加工
    , DATAEDIT.DATA_EDIT_ID AS DP_DATA_EDIT_ID--データ加工ID
    , DATAEDIT.EXECUTE_NO --データ加工表示順
    , DATAEDIT.STATUS AS DP_STATUS--データ加工状態
    , NEWITEM.NEW_ITEM_NAME
    , NEWITEM.NEW_ANSWER_TYPE
    , NEWITEM.NEW_LV1TITLE
    , NEWITEM.NEW_LV2TITLE
    , NVL(NEWCATE.CATECNT, 0) AS DP_CATEGORY_COUNT
FROM 
    T_ITEM_INFO ITEM 
    --カテゴリ数の取得
    LEFT OUTER JOIN (SELECT ITEM_INFO_ID, COUNT(*) AS CATECNT FROM T_CATEGORY_INFO GROUP BY ITEM_INFO_ID) ITEMCATE 
    ON ITEM.ITEM_INFO_ID = ITEMCATE.ITEM_INFO_ID
    --子アイテムの場合は、そのアイテムの親アイテムをマトリクス情報より得てカテゴリ数を取得する
    LEFT OUTER JOIN T_MATRIX_INFO MATRIX 
    ON ITEM.ITEM_INFO_ID = MATRIX.CHILD_ITEM_INFO_ID
    LEFT OUTER JOIN (SELECT ITEM_INFO_ID, COUNT(*) AS CATECNT FROM T_CATEGORY_INFO GROUP BY ITEM_INFO_ID) PARENTCATE 
    ON MATRIX.ITEM_INFO_ID = PARENTCATE.ITEM_INFO_ID
    --子アイテム数の取得
    LEFT OUTER JOIN (SELECT ITEM_INFO_ID, COUNT(*) AS CHILDITEMCNT FROM T_MATRIX_INFO GROUP BY ITEM_INFO_ID) MATRIXCOUNT 
    ON ITEM.ITEM_INFO_ID = MATRIXCOUNT.ITEM_INFO_ID
    --データ加工
    LEFT OUTER JOIN T_DATA_EDIT_LIST DATAEDIT 
    ON ITEM.DATA_EDIT_ID = DATAEDIT.DATA_EDIT_ID 
    LEFT OUTER JOIN T_DATA_PROCESS_NEW_ITEM NEWITEM 
    ON DATAEDIT.DATA_EDIT_ID = NEWITEM.DATA_EDIT_ID
    LEFT OUTER JOIN (SELECT DATA_EDIT_ID, COUNT(*) AS CATECNT FROM T_DATA_PROCESS_NEW_CATEGORY GROUP BY DATA_EDIT_ID) NEWCATE 
    ON NEWITEM.DATA_EDIT_ID = NEWCATE.DATA_EDIT_ID
WHERE 
        ITEM.QCWEBID = /*pmb.QCWebId*/5 
	AND ITEM.STATUS IN (1, 2) --有効と仮登録
	AND ITEM.SOURCE_DIV IN ('0', '1') --Originalと加工データ
    AND NVL(NEWITEM.NEW_ANSWER_TYPE, ITEM.ANSWER_TYPE) IN /*pmb.AnswerType*/('1','2','3','4')
    AND (DATAEDIT.EXECUTE_NO IS NULL OR DATAEDIT.EXECUTE_NO < /*pmb.ExecuteNo*/99999 ) --指定のデータ加工表示順より後ろのアイテム情報を表示しない
    AND (DATAEDIT.DELETE_RESERVE_FLAG IS NULL OR DATAEDIT.DELETE_RESERVE_FLAG = 0) --削除予約中のデータ加工に紐づくアイテム情報を表示しない
ORDER BY 
    ITEM.SORT_NUMBER ASC, ITEM.MATRIX_DIV ASC
;