/*
[df:title]
出力物の作成依頼キューの取得

[df:description]
リクエストIDを指定して検索します
以下の条件値は必須です
・OutputRequestId
*/
-- #TOutputReportsetInfoRequest#
-- !TOutputReportsetInfoRequestPmb!
-- !!Decimal OutputRequestId!!

SELECT
	REQUEST.OUTPUT_REQUEST_ID
	,REQUEST.QCWEBID
	,REQUEST.REQUEST_SERVER_CODE
	,REQUEST.DOWNLOAD_PATH
	,REQUEST.PROC_SERVER_CODE
	,REQUEST.VIEW_SURVEY_NAME
	,REQUEST.EXCELBOOK_TYPE
	,REQUEST.NUMERIC_ANSWER_VIEW_CODE
	,REQUEST.DP_TOTAL
	,REQUEST.DP_AVERAGE
	,REQUEST.DP_STANDARD_DIV
	,REQUEST.DP_MIN
	,REQUEST.DP_MAX
	,REQUEST.DP_MEDIAN
	,REQUEST.DP_WEIGHT
	,REQUEST.DP_WEIGHTAVR
	,REQUEST.Language
	,REQUEST.SHOW_ZERO_NA_IV_CODE
	,REQUEST.MERGE_AXIS_CELLS_FLAG
	,REQUEST.PROC_WEIGHT
	,REPORTSET.OUTPUT_REPORTSET_INFO_ID
	,REPORTSET.OUTPUT_FILE_TYPE_CODE
	,REPORTSET.REPORT_FILEN_NAME_PREFIX
	,REPORTSET.COMMENT_OUTPUT_FLAG
	,REPORTSET.POWERPOINT_TYPE
	,TEMPLATE.OUTPUT_TEMPLATE_ID
	,TEMPLATE.UPLOAD_PATH
	,MASTER.PATH
	,COMMON.OUTPUT_COMMON_ID
	,COMMON.OUTPUT_TYPE
	,COMMON.TSV_FILE_PATH
	,COMMON.EXCELBOOK_NAME_PREFIX
	,COMMON.WB_SETTING_CODE
	,COMMON.NOANSWER_VISIBLE_CODE
	,COMMON.UNMATCH_VISIBLE_CODE
	,SURVEY.UTF8_FLAG
FROM
	T_OUTPUT_REPORTSET_INFO REPORTSET LEFT JOIN T_OUTPUT_REQUEST REQUEST ON
		REPORTSET.OUTPUT_REPORTSET_INFO_ID = REQUEST.OUTPUT_REPORTSET_INFO_ID
	LEFT JOIN T_OUTPUT_COMMON COMMON ON
		REQUEST.OUTPUT_REQUEST_ID = COMMON.OUTPUT_REQUEST_ID
	INNER JOIN T_QCWEB_SURVEY_INFO SURVEY ON
		REQUEST.QCWEBID = SURVEY.QCWEBID
	LEFT JOIN T_OUTPUT_TEMPLATE TEMPLATE ON
		REPORTSET.OUTPUT_TEMPLATE_ID = TEMPLATE.OUTPUT_TEMPLATE_ID
	LEFT JOIN T_OUTPUT_TEMPLATE_MASTER MASTER ON
		TEMPLATE.OUTPUT_TEMPLATE_MASTER_ID = MASTER.OUTPUT_TEMPLATE_MASTER_ID
WHERE
	REQUEST.OUTPUT_REQUEST_ID = /*pmb.OutputRequestId*/1
ORDER BY
	COMMON.ORDER_COUNT ASC
;
