/*
[df:title]
シナリオにパラメータのアイテムが使用されているか調査する（データ加工の整合性チェック用）

[df:description]
指定されたアイテムIDを利用しているシナリオの情報を調査する。

TScenarioTotalizationBhv_SelectItemBeingUsed.sql
*/
-- #ScenarioSelectItemBeingUsedEntity#

-- !TScenarioSelectItemBeingUsedPmb!
-- !!decimal Qcwebid!!
-- !!decimal ItemInfoId!!

SELECT 
  SCENARIOID
, SCENARIOTYPE
, SCENARIONAME
, SUM(WB) AS WB
, SUM(WBCODE) AS WBCODE
, SUM(QUERY) AS QUERYLIST
, SUM(TARGET) AS TARGET
, SUM(AXIS) AS AXIS
, SUM(FAADD) AS FAADD
FROM
(
	--ウエイトバックコード
	SELECT
	  NULL AS SCENARIOID
	, NULL AS SCENARIOTYPE
	, NULL AS SCENARIONAME
	, 99999 AS SORTNO
	, 1 AS WB
	, 0 AS WBCODE
	, 0 AS QUERY
	, 0 AS TARGET
	, 0 AS AXIS
	, 0 AS FAADD
	FROM T_WEIGHTBACK A
	WHERE A.QCWEBID = /*pmb.Qcwebid*/5
	AND A.WEIGHTBACK_ITEM_ID = /*pmb.ItemInfoId*/27
	--ウエイトバックコード
	UNION ALL
	SELECT
	  A.SCENARIO_TOTALIZATION_ID AS SCENARIOID
	, A.SCENARIO_TYPE AS SCENARIOTYPE
	, A.SCENARIO_NAME AS SCENARIONAME
	, A.SORT_NO AS SORTNO
	, 0 AS WB
	, 1 AS WBCODE
	, 0 AS QUERY
	, 0 AS TARGET
	, 0 AS AXIS
	, 0 AS FAADD
	FROM T_SCENARIO_TOTALIZATION A
	WHERE A.QCWEBID = /*pmb.Qcwebid*/5
	AND A.WEIGHTBACK_CODE = /*pmb.ItemInfoId*/27
	--絞込み条件
	UNION ALL
	SELECT 
	  A.SCENARIO_TOTALIZATION_ID AS SCENARIOID
	, A.SCENARIO_TYPE AS SCENARIOTYPE
	, A.SCENARIO_NAME AS SCENARIONAME
	, A.SORT_NO AS SORTNO
	, 0 AS WB
	, 0 AS WBCODE
	, 1 AS QUERY
	, 0 AS TARGET
	, 0 AS AXIS
	, 0 AS FAADD
	FROM T_SCENARIO_TOTALIZATION A, T_SCENARIO_QUERYLIST B
	WHERE A.QCWEBID = /*pmb.Qcwebid*/5
	AND A.SCENARIO_TOTALIZATION_ID = B.SCENARIO_TOTALIZATION_ID
	AND (B.ITEM_INFO_ID = /*pmb.ItemInfoId*/27 
	     OR B.CONDITION_STRING = (SELECT ITEM_NAME FROM T_ITEM_INFO WHERE QCWEBID = /*pmb.Qcwebid*/5 AND ITEM_INFO_ID = /*pmb.ItemInfoId*/27))
	--GTシナリオアイテム
	UNION ALL
	SELECT
	  A.SCENARIO_TOTALIZATION_ID AS SCENARIOID
	, A.SCENARIO_TYPE AS SCENARIOTYPE
	, A.SCENARIO_NAME AS SCENARIONAME
	, A.SORT_NO AS SORTNO
	, 0 AS WB
	, 0 AS WBCODE
	, 0 AS QUERY
	, 1 AS TARGET
	, 0 AS AXIS
	, 0 AS FAADD
	FROM T_SCENARIO_TOTALIZATION A, T_GT_SCENARIO_ITEM B
	WHERE A.QCWEBID = /*pmb.Qcwebid*/5
	AND A.SCENARIO_TOTALIZATION_ID = B.SCENARIO_TOTALIZATION_ID
	AND B.ITEM_INFO_ID = /*pmb.ItemInfoId*/27
	--クロス集計対象シナリオアイテム
	UNION ALL
	SELECT
	  A.SCENARIO_TOTALIZATION_ID AS SCENARIOID
	, A.SCENARIO_TYPE AS SCENARIOTYPE
	, A.SCENARIO_NAME AS SCENARIONAME
	, A.SORT_NO AS SORTNO
	, 0 AS WB
	, 0 AS WBCODE
	, 0 AS QUERY
	, 1 AS TARGET
	, 0 AS AXIS
	, 0 AS FAADD
	FROM T_SCENARIO_TOTALIZATION A, T_CROSS_SCENARIO_TARGET B
	WHERE A.QCWEBID = /*pmb.Qcwebid*/5
	AND A.SCENARIO_TOTALIZATION_ID = B.SCENARIO_TOTALIZATION_ID
	AND B.SC_ITEM_ID = /*pmb.ItemInfoId*/27
	--クロス集計軸シナリオアイテム
	UNION ALL
	SELECT
	  A.SCENARIO_TOTALIZATION_ID AS SCENARIOID
	, A.SCENARIO_TYPE AS SCENARIOTYPE
	, A.SCENARIO_NAME AS SCENARIONAME
	, A.SORT_NO AS SORTNO
	, 0 AS WB
	, 0 AS WBCODE
	, 0 AS QUERY
	, 0 AS TARGET
	, 1 AS AXIS
	, 0 AS FAADD
	FROM T_SCENARIO_TOTALIZATION A, T_CROSS_SCENARIO_TARGET B, T_CROSS_SCENARIO_ITEM C
	WHERE A.QCWEBID = /*pmb.Qcwebid*/5
	AND A.SCENARIO_TOTALIZATION_ID = B.SCENARIO_TOTALIZATION_ID
	AND B.CROSS_SCENARIO_TARGET_ID = C.CROSS_SCENARIO_TARGET_ID
	AND (C.AXIS1_ITEM_ID = /*pmb.ItemInfoId*/27 OR C.AXIS2_ITEM_ID = /*pmb.ItemInfoId*/27)
	--FAシナリオアイテム
	UNION ALL
	SELECT
	  A.SCENARIO_TOTALIZATION_ID AS SCENARIOID
	, A.SCENARIO_TYPE AS SCENARIOTYPE
	, A.SCENARIO_NAME AS SCENARIONAME
	, A.SORT_NO AS SORTNO
	, 0 AS WB
	, 0 AS WBCODE
	, 0 AS QUERY
	, 1 AS TARGET
	, 0 AS AXIS
	, 0 AS FAADD
	FROM T_SCENARIO_TOTALIZATION A, T_FA_SCENARIO_HEADER B, T_FA_SCENARIO_ITEM C
	WHERE A.QCWEBID = /*pmb.Qcwebid*/5
	AND A.SCENARIO_TOTALIZATION_ID = B.SCENARIO_TOTALIZATION_ID
	AND B.FA_SCENARIO_HEADER_ID = C.FA_SCENARIO_HEADER_ID
	AND C.FA_TARGET_ITEM_ID = /*pmb.ItemInfoId*/27
	--付加アイテム
	UNION ALL
	SELECT
	  A.SCENARIO_TOTALIZATION_ID AS SCENARIOID
	, A.SCENARIO_TYPE AS SCENARIOTYPE
	, A.SCENARIO_NAME AS SCENARIONAME
	, A.SORT_NO AS SORTNO
	, 0 AS WB
	, 0 AS WBCODE
	, 0 AS QUERY
	, 0 AS TARGET
	, 0 AS AXIS
	, 1 AS FAADD
	FROM T_SCENARIO_TOTALIZATION A, T_FA_SCENARIO_HEADER B, T_FA_LIST_ADD_ITEM C
	WHERE A.QCWEBID = /*pmb.Qcwebid*/5
	AND A.SCENARIO_TOTALIZATION_ID = B.SCENARIO_TOTALIZATION_ID
	AND B.FA_SCENARIO_HEADER_ID = C.FA_SCENARIO_HEADER_ID
	AND C.ITEM_INFO_ID = /*pmb.ItemInfoId*/27
)
GROUP BY SCENARIOID, SCENARIOTYPE, SCENARIONAME, SORTNO
ORDER BY SORTNO
