/*
[df:title]
QCWEB管理IDをキーにシナリオ情報のみを取得する（シナリオ区分での絞り込みが可能）

[df:description]
シナリオに紐づくアイテムの情報は取得しない


以下の条件値は必須です
・QCWebId

*/
-- #ScenarioNodesByQCWebIDEntity#

-- !TScenarioFindScenarioNodesByQCWebIDPmb!
-- !!decimal QCWebId!!
-- !!string ScenarioType!!

SELECT SCENARIO_TOTALIZATION_ID, SCENARIO_NAME, SCENARIO_TYPE, SORT_NO, WEIGHTBACK_FLAG, SUM(CNT) AS ITEM_COUNT, SUM(RCNT) AS REPORT_COUNT
FROM (
SELECT A.SCENARIO_TOTALIZATION_ID, A.SCENARIO_NAME, A.SCENARIO_TYPE, A.SORT_NO, A.WEIGHTBACK_FLAG
, CASE A.SCENARIO_TYPE
WHEN 'G' THEN (CASE WHEN G.SCENARIO_TOTALIZATION_ID IS NULL THEN 0 ELSE 1 END)
WHEN 'C' THEN (CASE WHEN C.SCENARIO_TOTALIZATION_ID IS NULL THEN 0 ELSE 1 END)
WHEN 'F' THEN (CASE WHEN F.SCENARIO_TOTALIZATION_ID IS NULL THEN 0 ELSE 1 END)
END CNT
, CASE A.SCENARIO_TYPE
WHEN 'G' THEN (CASE WHEN GR.REPORT_ID IS NULL THEN 0 ELSE 1 END)
WHEN 'C' THEN (CASE WHEN CR.REPORT_ID IS NULL THEN 0 ELSE 1 END)
WHEN 'F' THEN (CASE WHEN FR.REPORT_ID IS NULL THEN 0 ELSE 1 END)
END RCNT
FROM T_SCENARIO_TOTALIZATION A
, T_GT_SCENARIO_ITEM G
, T_CROSS_SCENARIO_TARGET C
, T_FA_SCENARIO_HEADER F
, (SELECT R.REPORT_ID, R.TARGET_SCENARIO_ITEM_ID FROM T_REPORTSET RS, T_REPORT R 
   WHERE RS.QCWEBID = /*pmb.QCWebId*/194 AND RS.REPORTSET_ID = R.REPORTSET_ID AND R.SCENARIO_TYPE = 'G') GR
, (SELECT R.REPORT_ID, R.TARGET_SCENARIO_ITEM_ID FROM T_REPORTSET RS, T_REPORT R 
   WHERE RS.QCWEBID = /*pmb.QCWebId*/194 AND RS.REPORTSET_ID = R.REPORTSET_ID AND R.SCENARIO_TYPE = 'C') CR
, (SELECT R.REPORT_ID, R.TARGET_SCENARIO_ITEM_ID FROM T_REPORTSET RS, T_REPORT R 
   WHERE RS.QCWEBID = /*pmb.QCWebId*/194 AND RS.REPORTSET_ID = R.REPORTSET_ID AND R.SCENARIO_TYPE = 'F') FR
WHERE A.QCWEBID = /*pmb.QCWebId*/194
/*IF pmb.ScenarioType != null*/
AND A.SCENARIO_TYPE = /*pmb.ScenarioType*/'F'
/*END*/
AND A.SCENARIO_TOTALIZATION_ID = G.SCENARIO_TOTALIZATION_ID(+)
AND A.SCENARIO_TOTALIZATION_ID = C.SCENARIO_TOTALIZATION_ID(+)
AND A.SCENARIO_TOTALIZATION_ID = F.SCENARIO_TOTALIZATION_ID(+)
AND G.GT_SCENARIO_ITEM_ID = GR.TARGET_SCENARIO_ITEM_ID(+)
AND C.CROSS_SCENARIO_TARGET_ID = CR.TARGET_SCENARIO_ITEM_ID(+)
AND F.FA_SCENARIO_HEADER_ID = FR.TARGET_SCENARIO_ITEM_ID(+)
)
GROUP BY SCENARIO_TOTALIZATION_ID, SCENARIO_NAME, SCENARIO_TYPE, SORT_NO, WEIGHTBACK_FLAG
ORDER BY SORT_NO
